(base) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_wee k1
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_sit e.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 16:43:02] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in top-level template code
    <link rel="stylesheet" href="{{ url_for('static', 'sb-cp.css') }}" media="screen">
TypeError: url_for() takes 1 positional argument but 2 were given
127.0.0.1 - - [30/Jun/2021 16:43:02] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:43:02] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:43:03] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:43:03] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:43:03] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:43:03] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py', reloading
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 16:45:01] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 16:45:01] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/duck2.gif HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate  nlp_week1[K[K[K[K[K[K[K[K[K[KM[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
[KM[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[Kconda activate nlp_week1
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ 
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_week1
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_week1conda a[K[K[K[K[K[K[K
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate  nlp_week1
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple .p[K[K_site.pu[Ky
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:27:34] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:32:06] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:32:06] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:32:06] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:32:06] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:32:06] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:32:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:32:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:26] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:33:29] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:29] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:29] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:30] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:34] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:33:35] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ ^C
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:34:03] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:34:04] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:34:04] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:34:04] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:34:04] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:34:04] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.pyM(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_week1M(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_[3Psite.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:35:33] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}"
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:35:33] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:35:33] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:35:33] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:35:33] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:35:33] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:40:22] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}"
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:40:23] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:40:23] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:40:23] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:40:23] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:40:24] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.pyM(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_week1M(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_[3Psite.pyM(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ conda activate nlp_week1M(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_[3Psite.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:47:36] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:47:37] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/pirate.gif HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:47:37] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/elves HTTP/1.1[0m" 404 -
127.0.0.1 - - [30/Jun/2021 17:49:26] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:49:27] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/duck2.gif HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:49:27] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/pirate.gif HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:49:27] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/static/elves.png HTTP/1.1[0m" 404 -
^F^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33346/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 17:53:14] "[35m[1mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py", line 30, in home
    return render_template('sb-cp.html', name=name)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/templates/sb-cp.html", line 12, in template
    <script class="u-script" type="text/javascript" src="{{ url_for('static', filename=‘jquery-1.9.1.min.js’)}}"
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 656
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 17:53:15] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33346/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
Traceback (most recent call last):
  File "simple_site.py", line 35, in <module>
    app.run(host = '0.0.0.0', port = port, debug=True)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33346/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
Traceback (most recent call last):
  File "simple_site.py", line 35, in <module>
    app.run(host = '0.0.0.0', port = port, debug=True)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/projects/ead608b4-11ae-4096-9660-05de74074fc1/miniconda3/envs/nlp_week1/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33344/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 18:01:19] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:01:19] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/nicepage.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:01:19] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/sb-cp.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:01:19] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/jquery-1.9.1.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:01:19] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/nicepage.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:01:20] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/image/spongebob.png HTTP/1.1[0m" 404 -
127.0.0.1 - - [30/Jun/2021 18:01:20] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/images/spongebob.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:10:36] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:10:38] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/image/spongebob.png HTTP/1.1[0m" 404 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33344/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 18:11:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:11:08] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/image/spongebob.png HTTP/1.1[0m" 404 -
127.0.0.1 - - [30/Jun/2021 18:11:23] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/About-us.html HTTP/1.1[0m" 404 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33344/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 18:13:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:13:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/duck2.gif HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:13:07] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/pirate.gif HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:13:08] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/elves.png HTTP/1.1[0m" 404 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33344/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 18:19:46] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:19:46] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/ms-cp.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:19:46] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/static/images/michael.jpg HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 18:20:17] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/About-us.html HTTP/1.1[0m" 404 -
^C(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ [K(nlp_week1) ]0;~/website/character_bot_web/app[01;34m~/website/character_bot_web/app[00m$ python simple_site.py
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Serving Flask app "simple_site" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on http://0.0.0.0:33344/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
127.0.0.1 - - [30/Jun/2021 20:49:29] "[37mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/ HTTP/1.1[0m" 200 -
127.0.0.1 - - [30/Jun/2021 20:49:32] "[33mGET /ead608b4-11ae-4096-9660-05de74074fc1/port/33344/Page-1.html HTTP/1.1[0m" 404 -
 * Detected change in '/projects/ead608b4-11ae-4096-9660-05de74074fc1/website/character_bot_web/app/simple_site.py', reloading
 * Restarting with stat
Try to open

    https://cocalc5.ai-camp.org/ead608b4-11ae-4096-9660-05de74074fc1/port/33344/


 * Debugger is active!
 * Debugger PIN: 137-102-814
